// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9j1njkegaa_ldqDKkRMhViVYiKv17_D4',
    appId: '1:751324797630:web:55323767747e690bf39cef',
    messagingSenderId: '751324797630',
    projectId: 'projeto-flutterchat',
    authDomain: 'projeto-flutterchat.firebaseapp.com',
    storageBucket: 'projeto-flutterchat.appspot.com',
    measurementId: 'G-GNBQ7SJ9XW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuj9EMBBHUAN3nsxoY7eAF5GMBxKgac1w',
    appId: '1:751324797630:android:a1c9323812952982f39cef',
    messagingSenderId: '751324797630',
    projectId: 'projeto-flutterchat',
    storageBucket: 'projeto-flutterchat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpNfOOOPHvk_cXJtHpsVxfLQ69b0_UiXA',
    appId: '1:751324797630:ios:600c172d8c4dff08f39cef',
    messagingSenderId: '751324797630',
    projectId: 'projeto-flutterchat',
    storageBucket: 'projeto-flutterchat.appspot.com',
    iosClientId: '751324797630-9c3e4a13eq3jqh3j9p18star5pibt4be.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpNfOOOPHvk_cXJtHpsVxfLQ69b0_UiXA',
    appId: '1:751324797630:ios:600c172d8c4dff08f39cef',
    messagingSenderId: '751324797630',
    projectId: 'projeto-flutterchat',
    storageBucket: 'projeto-flutterchat.appspot.com',
    iosClientId: '751324797630-9c3e4a13eq3jqh3j9p18star5pibt4be.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterchat',
  );
}
